name: Build Docs

on: [push]

jobs:
  docs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python # Set Python version
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          poetry install -v
      - name: Update docs
        run: |
          poetry run python -m pip install mkdocs
          poetry run python -m pip install -r docs/requirements.txt
          cd docs
          cp ../README.md index.md
          cp ../logo.png ./
          cd ..
          poetry run mkdocs gh-deploy --clean --force
        if: success()

  fix-index:
    needs: docs
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
      - uses: actions/checkout@v2
        with:
          ref: gh-pages
      - name: Fix index.html
        run: |
          echo ':: head of index.html - before ::'
          head index.html
          sed -i '1,5{/^$/d}' index.html
          echo ':: head of index.html - after ::'
          head index.html
        if: success()
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Add changes" -a
        if: success()
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
        if: success()
